#!/usr/bin/sh

live_profile() {
	driver=${driver:-prop}
	lang=${lang:-en_US}
	keytable=${keytable:-us}
	tz=${tz:-"Etc/UTC"}
}

run_hook() {
	for mod in dm_mod dm-raid raid0 raid1 raid456 loop; do
		modprobe $mod || true
	done
	if [ -f /ventoy/hook/arch/ventoy-disk.sh ]; then
		echo "Loading Ventoy hooks"
		sh /ventoy/hook/arch/ventoy-disk.sh || true
		sleep 0.3
	fi
	export mount_handler="extos_mount_handler"
}
